name: Run Tests

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9' # Set this to an available Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply migrations
      run: |
        python manage.py migrate

    - name: Seed the database
      run: |
        # Add your commands to seed the database here
        # For example, you might load fixtures:
        python manage.py loaddata myfixture.json
        # Or you might have a custom management command:
        python manage.py seed_database

    - name: Run tests
      run: |
        python manage.py test